### ISSUE TITLE
Read versions.json and store a list of supported versions in the DB

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/ext-api.ulauncher.io#1]
Now we have two supported API versions 1 (old) and 2 (new).
New Ulauncher (v5) will require extensions to have `version.json` file in the master branch.
Like this one: https://github.com/Ulauncher/ulauncher-demo-ext/blob/master/versions.json
It will read the file to find out where to get the code for current Ulauncher API.

Users should be able to filter extensions on the [website](ext.ulauncher.io) by supported versions, hence we have to store what versions an extension supports in the DB.

**Technical Details**

* Before adding an extension, read `versions.json` file from the `master` branch
* Validate it by checking that it contains at least one object in a list with a non-empty `required_api_version` property
* Otherwise throw error: "Invalid versions.json. It must define at least one supported version"
* Drop manifest validation. Ulauncher will do that when user tries to install an extension
* Save a list of supported versions in a new property `SupportedVersions` of Extension document.  
  For example, for [this](https://github.com/Ulauncher/ulauncher-demo-ext/blob/master/versions.json) extension it should store the following data:  
  ```
  {
     ...
     "SupportedVersions": ["^1.0.0", "^2.0.0"]
  }
  ```

**Comment by CameronNemo** [comment]
Where are extensions added? Looking at `ext_api.models.extensions`, `put_extension` seems to be the place to add this check, but I thought you would have an idea of where to place this check.

**Comment by gornostal** [comment]
@CameronNemo in `server.py` on the line 138 we call `validate_manifest`. I think we could replace that with a call to get a list of supported versions from the JSON file
