### ISSUE TITLE
unable to submit extension keep getting Connection error!

### ISSUE THREAD

**Issue by barathbheeman** [Ulauncher/ext-api.ulauncher.io#13]
I wrote a small simple extension (following the documentation tutorial) to list all vs code workspaces and open the selected workspace in vs code upon selection. When I tried to submit the extension, after logging in to the https://ext.ulauncher.io/, I paste my repo's url and I get the  "Connection error!" message under the url box.

### Steps to reproduce

Not sure how you'd reproduce without logging in to my account.

1. Here's the link to my public repo for the extension: https://github.com/barathbheeman/vsw-extension
2. paste the link to  the https://ext.ulauncher.io/new 
3. click Next ->

### Current behavior

I get the message "Connection error!" underneath the entry box

### Expected behavior
Proceed with submission(?)

### Screenshots

![image](https://user-images.githubusercontent.com/23279260/135170972-4ad10e0c-fbd5-4b75-b0f3-4d6dc5aab5b6.png)

If I open the chrome console, I see this error:

`Access to fetch at 'https://ext-api.ulauncher.io/validate-project?url=https://github.com/barathbheeman/vsw-extension' from origin 'https://ext.ulauncher.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**Comment by gornostal** [comment]
Accidentally closed by a commit.
Still need to test and deploy the fix.

**Comment by gornostal** [comment]
Apologies for the delayed response @barathbheeman

There was missing error handler in the API (now it's fixed) which caused an HTTP 500 because of the redundant comma here https://github.com/barathbheeman/vsw-extension/pull/1

It should work once you merge my PR
