### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by xRealNeon** [Ulauncher/ext-api.ulauncher.io#18]
### Steps to reproduce
1. Go to `Submit New`
2. Add repo link
3. Click on `Next`

### Current behavior
Gives `HTTP Error 401: Unauthorized` error

### Expected behavior
Should add extension

### Screenshots
![grafik](https://user-images.githubusercontent.com/20997346/207141957-86519ec4-7491-427a-8eb4-21260db5f900.png)

**Comment by 1fexd** [comment]
Same here: 
![image](https://user-images.githubusercontent.com/58902674/216910194-14eb6f70-4f8a-4960-a34b-86200349a767.png)

**Comment by friday** [comment]
I'm going to guess this is because of @gornostal's GitHub API key expiring. It also killed our deploy script when it happened, but I was able to replace that with a newly generated one of my own.

I don't have access to fix this though.

**Comment by friday** [comment]
Also, thanks everyone for your patience and making me aware of this. I wasn't subbed to these repos, but I am now.

**Comment by gornostal** [comment]
Thanks for reporting @xRealNeon!
I'll look into this.

**Comment by gornostal** [comment]
Sorry for the inconvenience.
The issue is fixed now. I was able to submit a new extension.
